### ISSUE TITLE
Plugin fails when querying un-edited "Sample Project"

### ISSUE THREAD

**Issue by seangwright** [CMeeg/gridsome-source-kentico-cloud#2]
Hello!

I was exploring Gridsome and Kentico Cloud and was using your plugin to query for data.

I ran into an issue when trying to query from the Kentico Cloud demo project "Sample Project"

The line that fails is below

https://github.com/CMeeg/gridsome-source-kentico-cloud/blob/993313d6cc3656ee1692ff8139dd5f8ee5192f90/src/KenticoCloudSource.js#L181

The error is `Cannot read property 'isComponent' of null`

I resolved this issue by changing the line to `if (!!collectionNode && !collectionNode.isComponent) {`.

I'm also getting a large number of warnings about assets with duplicate keys being added:

```
Asset > Failed to add node: Duplicate key for property id: ...
```

I believe that the fields that are causing these warnings are `metadataTwitterImage` and `metadataOgImage`.

**Comment by CMeeg** [comment]
Thanks for flagging these Sean. I will take a look.

**Comment by seangwright** [comment]
I updated Gridsome (I was previously using `0.6.9`) to the current latest (`0.7.2`) and ran into an issue with Taxonomies... specifically `ManufacturerTaxonomy` (this is running on the same "Sample Project").

Here's my stacktrace

```
Load sources - 2.08s
Error: Cannot get field 'terms' from type 'TaxonomyManufacturer'. Field does not exist.
    at ObjectTypeComposer.getField (D:\path\to\app\node_modules\graphql-compose\lib\ObjectTypeComposer.js:167:13)
    at ObjectTypeComposer.isFieldPlural (D:\path\to\app\node_modules\graphql-compose\lib\ObjectTypeComposer.js:365:23)
    at mapValues (D:\path\to\app\node_modules\gridsome\lib\graphql\nodes\index.js:260:25)
    at D:\path\to\app\node_modules\lodash\lodash.js:13401:38
    at D:\path\to\app\node_modules\lodash\lodash.js:4905:15
    at baseForOwn (D:\path\to\app\node_modules\lodash\lodash.js:2990:24)
    at mapValues (D:\path\to\app\node_modules\lodash\lodash.js:13400:7)
    at createReferenceFields (D:\path\to\app\node_modules\gridsome\lib\graphql\nodes\index.js:257:16)
    at createNodesSchema (D:\path\to\app\node_modules\gridsome\lib\graphql\nodes\index.js:30:5)
    at createSchema (D:\path\to\app\node_modules\gridsome\lib\graphql\createSchema.js:59:3)
    at Schema.buildSchema (D:\path\to\app\node_modules\gridsome\lib\app\Schema.js:28:28)
    at Plugins.createSchema (D:\path\to\app\node_modules\gridsome\lib\app\Plugins.js:93:22)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

I have a feeling this is related to changes in the Kentico SDK / Cloud API.

I wanted to dig into this more and learn how the plugin was working.

I started with `export DEBUG=*` to turn on the `debug` package you're using.

But then I wanted to look at the data structures being processed and started using this `launch.json` for VS Code to debug the entire data load process.

```
{
    "version": "0.2.0",
    "configurations": [{
        "type": "node",
        "request": "launch",
        "name": "Launch Program",
        "program": "${workspaceRoot}\\node_modules\\gridsome\\bin\\gridsome.js",
        "runtimeArgs": [
            "--inspect-brk=9229",
        ],
        "args": [
            "develop"
        ],
        "port": 9229
    }]
}
```

The `export DEBUG=*` might be helpful to put in the README for devs looking to diagnose issues.

I think the `launch.json` might be helpful in the Gridsome repo to help plugin developers, but I thought I'd mention it here in case anyone else is interested.

**Comment by CMeeg** [comment]
Hi @seangwright 

Thanks for all the feedback so far :) I broke this issue down so it was easier for me to manage and hopefully the bugs fixed so far will mean you can get going on this again!

I have pushed a new version of the plugin (0.1.1) up to npm that should resolve the original two issues that you had with the Sample Project - see issues #3 and #4.

I have left a question for you on #5 if you have some time to get back to me on that.

I will need to investigate #6 another night - I haven't caught up with any new Gridsome or Kentico Cloud SDK releases yet so not sure where the problem lies, but as long as you don't mind rolling back to Gridsome 0.6.9 you should be OK - I set up a fresh Gridsome site on 0.6.9 (and Kentico Cloud Delivery 5.7.2) this evening to debug and fix the above issues and the Sample Project is pulling in without errors.

Thanks also for the `launch.json` config - probably worth raising with Gridsome as you say as it would be useful to have that in their repo or their docs.

Cheers

**Comment by seangwright** [comment]
Hey! thanks so much for responding and fixing these issues 🙏🙏!

I'm cool to roll back to `0.6.9` - I only upgraded to a newer Gridsome to see if any issues were resolved there.

I want to dig into the Gridsome API docs a lot more so I can better understand how all of this plumbing works and hopefully help diagnose any issues that appear (which I'm sure there will be more of with the Gridsome and Kentico packages updating so quickly).
